basePath: /api
definitions:
  common.BaseApiResponse-any:
    properties:
      data: {}
      http_request_status:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  common.BaseApiResponse-bool:
    properties:
      data:
        type: boolean
      http_request_status:
        type: integer
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.LoginRequest:
    properties:
      password:
        minLength: 8
        type: string
      phone_number:
        type: string
    required:
    - password
    - phone_number
    type: object
  dto.RefreshTokenRequest:
    properties:
      refresh_token:
        minLength: 8
        type: string
      token:
        type: string
    required:
    - refresh_token
    - token
    type: object
  dto.RegisterRequest:
    properties:
      password:
        minLength: 8
        type: string
      phone_number:
        type: string
    required:
    - password
    - phone_number
    type: object
  model.CreateOrderRequest:
    properties:
      amount:
        description: Amount to buy/sell
        type: number
      currency:
        description: Currency code (e.g., "ADA")
        type: string
      price:
        description: Price in USDT
        type: number
      side:
        description: '"buy" or "sell"'
        type: string
      stopLoss:
        allOf:
        - $ref: '#/definitions/model.StopLossConfig'
        description: Stop loss configuration
      takeProfit:
        allOf:
        - $ref: '#/definitions/model.TakeProfitConfig'
        description: Optional parameters for TP/SL
      type:
        description: '"limit" or "market"'
        type: string
    required:
    - amount
    - currency
    - price
    - side
    - type
    type: object
  model.MockAddRequest:
    type: object
  model.MockUpdateRequest:
    type: object
  model.Okx:
    properties:
      _id:
        type: string
      created_at:
        type: string
    type: object
  model.StopLossConfig:
    properties:
      amount:
        description: Amount to sell at stop loss
        type: number
      price:
        description: Stop loss price
        type: number
      triggerBy:
        description: '"last" or "index" or "mark"'
        type: string
    required:
    - amount
    - price
    type: object
  model.TakeProfitConfig:
    properties:
      amount:
        description: Amount to sell at take profit
        type: number
      price:
        description: Take profit price
        type: number
      triggerBy:
        description: '"last" or "index" or "mark"'
        type: string
    required:
    - amount
    - price
    type: object
  model.User:
    properties:
      _id:
        type: string
      created_at:
        type: string
      phone_number:
        type: string
    type: object
  model.UserAddRequest:
    properties:
      password:
        type: string
      phone_number:
        type: string
    required:
    - password
    - phone_number
    type: object
  model.UserUpdatePasswordRequest:
    properties:
      new_password:
        minLength: 8
        type: string
      new_password_confirmation:
        minLength: 8
        type: string
      old_password:
        minLength: 8
        type: string
    required:
    - new_password
    - new_password_confirmation
    - old_password
    type: object
  model.UserUpdateRequest:
    type: object
host: localhost:8080
info:
  contact: {}
  description: Description of the API
  title: WB Author API
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Verify Login with email and password
      parameters:
      - description: Verify Login
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/common.BaseApiResponse-bool'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
      summary: Verify Login with email and password
      tags:
      - Authentication
  /v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Get new AccessToken and RefreshToken
      parameters:
      - description: Register
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/common.BaseApiResponse-bool'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
      summary: Get new AccessToken and RefreshToken
      tags:
      - Authentication
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register with email and password
      parameters:
      - description: Register
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/common.BaseApiResponse-bool'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
      summary: Register with email and password
      tags:
      - Authentication
  /v1/create/mock:
    post:
      description: Create a new Okx
      parameters:
      - description: Create Okx
        in: body
        name: Okx
        required: true
        schema:
          $ref: '#/definitions/model.MockAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Okx'
      security:
      - Bearer: []
      summary: Create new Okx
      tags:
      - Okx
  /v1/create/order:
    post:
      consumes:
      - application/json
      description: Create a new order with specified currency and USDT pair
      parameters:
      - description: Order creation parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.BaseApiResponse-any'
      security:
      - Bearer: []
      summary: Create a new order
      tags:
      - Okx
  /v1/create/user:
    post:
      description: Create a new User
      parameters:
      - description: Create User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UserAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - Bearer: []
      summary: Create new User
      tags:
      - User
  /v1/delete/okx/{id}:
    delete:
      description: Delete a new Okx
      parameters:
      - description: Okx ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Okx'
      security:
      - Bearer: []
      summary: Delete new Okx
      tags:
      - Okx
  /v1/delete/user/{id}:
    delete:
      description: Delete a new User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - Bearer: []
      summary: Delete new User
      tags:
      - User
  /v1/get/mocks:
    get:
      description: Retrieve a list of Mocks based on provided filters and pagination
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page_number
        type: integer
      - default: 10
        description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Okx'
            type: array
      security:
      - Bearer: []
      summary: Get a list of Okx
      tags:
      - Okx
  /v1/get/okx-info:
    get:
      description: Return Okx
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Okx'
      security:
      - Bearer: []
      summary: Get Okx
      tags:
      - Okx
  /v1/get/okx/{id}:
    get:
      description: Return Okx
      parameters:
      - description: Okx ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Okx'
      security:
      - Bearer: []
      summary: Get Okx
      tags:
      - Okx
  /v1/get/user/{id}:
    get:
      description: Return User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - Bearer: []
      summary: Get User
      tags:
      - User
  /v1/get/users:
    get:
      description: Retrieve a list of Users based on provided filters and pagination
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page_number
        type: integer
      - default: 10
        description: Page size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      security:
      - Bearer: []
      summary: Get a list of User
      tags:
      - User
  /v1/update/okx/{id}:
    put:
      description: Update Okx
      parameters:
      - description: Okx ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Okx
        in: body
        name: Okx
        required: true
        schema:
          $ref: '#/definitions/model.MockUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Okx'
      security:
      - Bearer: []
      summary: Update Okx
      tags:
      - Okx
  /v1/update/password/user/{id}:
    put:
      description: Update User Password
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - Bearer: []
      summary: Update User Password
      tags:
      - User
  /v1/update/user/{id}:
    put:
      description: Update User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - Bearer: []
      summary: Update User
      tags:
      - User
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
